//start at 0:22 to 1:05
int ledPins[] = {4,5,6,7,8,9,10,11,12,13};


void setup()
{
  int index;

  for(index = 0; index <= 9; index++)
  {
    pinMode(ledPins[index],OUTPUT);
  }
}


void loop()
{
  oneAfterAnotherNoLoop();  
       
}
void oneAfterAnotherNoLoop()
{
  int delayTime=20;
  digitalWrite(ledPins[0], HIGH);  
  delay(400);            
  digitalWrite(ledPins[0], LOW);  
  digitalWrite(ledPins[1], HIGH); 
  delay(300);            
  digitalWrite(ledPins[1], LOW);   
  digitalWrite(ledPins[2], HIGH);  
  delay(300);                
  digitalWrite(ledPins[2], LOW); 
  digitalWrite(ledPins[3], HIGH);  
  delay(300);                
  digitalWrite(ledPins[3], LOW); 
  digitalWrite(ledPins[4], HIGH);  
  delay(100);                
  digitalWrite(ledPins[4], LOW); 
  digitalWrite(ledPins[5], HIGH);  
  delay(200);             
  digitalWrite(ledPins[5], LOW);    
  digitalWrite(ledPins[6], HIGH);  
  delay(200);       
  digitalWrite(ledPins[6], LOW);          
  digitalWrite(ledPins[7], HIGH);  
  delay(400);               
  digitalWrite(ledPins[7], LOW); 
  digitalWrite(ledPins[8], HIGH);
  delay(200);           
  digitalWrite(ledPins[8], LOW);      
  digitalWrite(ledPins[9], HIGH); 
  delay(200);
  digitalWrite(ledPins[9], LOW); 
  
  digitalWrite(ledPins[0], HIGH);  
  delay(100);            
  digitalWrite(ledPins[0], LOW);  
  digitalWrite(ledPins[1], HIGH); 
  delay(150);            
  digitalWrite(ledPins[1], LOW);   
  digitalWrite(ledPins[2], HIGH);  
  delay(100);                
  digitalWrite(ledPins[2], LOW); 
  digitalWrite(ledPins[3], HIGH);  
  delay(100);                
  digitalWrite(ledPins[3], LOW); 
  digitalWrite(ledPins[4], HIGH);  
  delay(150);                
  digitalWrite(ledPins[4], LOW); 
  digitalWrite(ledPins[5], HIGH);  
  delay(100);             
  digitalWrite(ledPins[5], LOW);    
  digitalWrite(ledPins[6], HIGH);  
  delay(100);       
  digitalWrite(ledPins[6], LOW);          
  digitalWrite(ledPins[7], HIGH);  
  delay(150);               
  digitalWrite(ledPins[7], LOW); 
  digitalWrite(ledPins[8], HIGH);
  delay(100);           
  digitalWrite(ledPins[8], LOW);      
  digitalWrite(ledPins[9], HIGH); 
  delay(100);
  digitalWrite(ledPins[9], LOW);
  digitalWrite(ledPins[4], HIGH);
  delay(delayTime);
  digitalWrite(ledPins[5], HIGH);    
  delay(delayTime);         
  digitalWrite(ledPins[3], HIGH);  
  delay(delayTime); 
  digitalWrite(ledPins[6], HIGH);  
  delay(delayTime); 
  digitalWrite(ledPins[2], HIGH);
  delay(delayTime);   
  digitalWrite(ledPins[7], HIGH); 
  delay(delayTime);  
  digitalWrite(ledPins[1], HIGH);
  delay(delayTime);   
  digitalWrite(ledPins[8], HIGH);
  delay(delayTime);
  digitalWrite(ledPins[0], HIGH);
  delay(delayTime);
  digitalWrite(ledPins[9], HIGH);
  delay(delayTime);
  digitalWrite(ledPins[9], LOW);
  delay(delayTime);
  digitalWrite(ledPins[0], LOW);
  delay(delayTime);             
  digitalWrite(ledPins[8], LOW);
  delay(delayTime);   
  digitalWrite(ledPins[1], LOW); 
  delay(delayTime);  
  digitalWrite(ledPins[7], LOW);
  delay(delayTime);   
  digitalWrite(ledPins[2], LOW);
  delay(delayTime);   
  digitalWrite(ledPins[6], LOW);
  delay(delayTime);   
  digitalWrite(ledPins[3], LOW);
  delay(delayTime);
  digitalWrite(ledPins[5], LOW);
  delay(delayTime);
  digitalWrite(ledPins[4], LOW);
  delay(delayTime);
  digitalWrite(ledPins[0], HIGH);
  delay(delayTime);
  digitalWrite(ledPins[9], HIGH);    
  delay(delayTime);         
  digitalWrite(ledPins[1], HIGH);  
  delay(delayTime); 
  digitalWrite(ledPins[8], HIGH);  
  delay(delayTime); 
  digitalWrite(ledPins[2], HIGH);
  delay(delayTime);   
  digitalWrite(ledPins[7], HIGH); 
  delay(delayTime);  
  digitalWrite(ledPins[3], HIGH);
  delay(delayTime);   
  digitalWrite(ledPins[6], HIGH);
  delay(delayTime);
  digitalWrite(ledPins[4], HIGH);
  delay(delayTime);
  digitalWrite(ledPins[5], HIGH);
  delay(delayTime);
  digitalWrite(ledPins[9], LOW);
  delay(delayTime);
  digitalWrite(ledPins[0], LOW);
  delay(delayTime);             
  digitalWrite(ledPins[1], LOW);
  delay(delayTime);   
  digitalWrite(ledPins[8], LOW); 
  delay(delayTime);  
  digitalWrite(ledPins[2], LOW);
  delay(delayTime);   
  digitalWrite(ledPins[7], LOW);
  delay(delayTime);   
  digitalWrite(ledPins[3], LOW);
  delay(delayTime);   
  digitalWrite(ledPins[6], LOW);
  delay(delayTime);
  digitalWrite(ledPins[4], LOW);
  delay(delayTime);
  digitalWrite(ledPins[5], LOW);
  delay(delayTime);
  
  digitalWrite(ledPins[4], HIGH);
  delay(delayTime);
  digitalWrite(ledPins[5], HIGH);    
  delay(delayTime);         
  digitalWrite(ledPins[3], HIGH);  
  delay(delayTime); 
  digitalWrite(ledPins[6], HIGH);  
  delay(delayTime); 
  digitalWrite(ledPins[2], HIGH);
  delay(delayTime);   
  digitalWrite(ledPins[7], HIGH); 
  delay(delayTime);  
  digitalWrite(ledPins[1], HIGH);
  delay(delayTime);   
  digitalWrite(ledPins[8], HIGH);
  delay(delayTime);
  digitalWrite(ledPins[0], HIGH);
  delay(delayTime);
  digitalWrite(ledPins[9], HIGH);
  delay(delayTime);
  digitalWrite(ledPins[9], LOW);
  delay(delayTime);
  digitalWrite(ledPins[0], LOW);
  delay(delayTime);             
  digitalWrite(ledPins[8], LOW);
  delay(delayTime);   
  digitalWrite(ledPins[1], LOW); 
  delay(delayTime);  
  digitalWrite(ledPins[7], LOW);
  delay(delayTime);   
  digitalWrite(ledPins[2], LOW);
  delay(delayTime);   
  digitalWrite(ledPins[6], LOW);
  delay(delayTime);   
  digitalWrite(ledPins[3], LOW);
  delay(delayTime);
  digitalWrite(ledPins[5], LOW);
  delay(delayTime);
  digitalWrite(ledPins[4], LOW);
  delay(delayTime);
  digitalWrite(ledPins[0], HIGH);
  delay(delayTime);
  digitalWrite(ledPins[9], HIGH);    
  delay(delayTime);         
  digitalWrite(ledPins[1], HIGH);  
  delay(delayTime); 
  digitalWrite(ledPins[8], HIGH);  
  delay(delayTime); 
  digitalWrite(ledPins[2], HIGH);
  delay(delayTime);   
  digitalWrite(ledPins[7], HIGH); 
  delay(delayTime);  
  digitalWrite(ledPins[3], HIGH);
  delay(delayTime);   
  digitalWrite(ledPins[6], HIGH);
  delay(delayTime);
  digitalWrite(ledPins[4], HIGH);
  delay(delayTime);
  digitalWrite(ledPins[5], HIGH);
  delay(delayTime);
  digitalWrite(ledPins[9], LOW);
  delay(delayTime);
  digitalWrite(ledPins[0], LOW);
  delay(delayTime);             
  digitalWrite(ledPins[1], LOW);
  delay(delayTime);   
  digitalWrite(ledPins[8], LOW); 
  delay(delayTime);  
  digitalWrite(ledPins[2], LOW);
  delay(delayTime);   
  digitalWrite(ledPins[7], LOW);
  delay(delayTime);   
  digitalWrite(ledPins[3], LOW);
  delay(delayTime);   
  digitalWrite(ledPins[6], LOW);
  delay(delayTime);
  digitalWrite(ledPins[4], LOW);
  delay(delayTime);
  digitalWrite(ledPins[5], LOW);
  delay(delayTime);  
  
  digitalWrite(ledPins[0], HIGH);  
  digitalWrite(ledPins[9], HIGH);
  delay(200);
  digitalWrite(ledPins[0], LOW);  
  digitalWrite(ledPins[9], LOW);
  delay(200);
  digitalWrite(ledPins[8], HIGH);  
  digitalWrite(ledPins[1], HIGH);
  delay(200);
  digitalWrite(ledPins[8], LOW);  
  digitalWrite(ledPins[1], LOW);
  delay(200);
  digitalWrite(ledPins[7], HIGH);  
  digitalWrite(ledPins[2], HIGH);
  delay(200);
  digitalWrite(ledPins[7], LOW);  
  digitalWrite(ledPins[2], LOW);
  delay(200);
  digitalWrite(ledPins[6], HIGH);  
  digitalWrite(ledPins[3], HIGH);
  delay(200);
  digitalWrite(ledPins[6], LOW);  
  digitalWrite(ledPins[3], LOW); 
  delay(200);
  digitalWrite(ledPins[5], HIGH);  
  digitalWrite(ledPins[4], HIGH);
  delay(200);
  digitalWrite(ledPins[5], LOW);  
  digitalWrite(ledPins[4], LOW);  
  delay(200);
  digitalWrite(ledPins[5], HIGH);  
  digitalWrite(ledPins[4], HIGH);
  delay(200);
  digitalWrite(ledPins[5], LOW);  
  digitalWrite(ledPins[4], LOW);
  delay(200);
  digitalWrite(ledPins[6], HIGH);  
  digitalWrite(ledPins[3], HIGH);
  delay(200);
  digitalWrite(ledPins[6], LOW);  
  digitalWrite(ledPins[3], LOW);
  delay(200);
  digitalWrite(ledPins[7], HIGH);  
  digitalWrite(ledPins[2], HIGH);
  delay(200);
  digitalWrite(ledPins[7], LOW);  
  digitalWrite(ledPins[2], LOW);
  delay(200);
  digitalWrite(ledPins[8], HIGH);  
  digitalWrite(ledPins[1], HIGH);
  delay(200);
  digitalWrite(ledPins[8], LOW);  
  digitalWrite(ledPins[1], LOW); 
  delay(200);
  digitalWrite(ledPins[9], HIGH);  
  digitalWrite(ledPins[0], HIGH);
  delay(200);
  digitalWrite(ledPins[9], LOW);  
  digitalWrite(ledPins[0], LOW);  
  delay(200);
  digitalWrite(ledPins[0], HIGH);  
  digitalWrite(ledPins[9], HIGH);
  delay(200);
  digitalWrite(ledPins[0], LOW);  
  digitalWrite(ledPins[9], LOW);
  delay(200);
  digitalWrite(ledPins[8], HIGH);  
  digitalWrite(ledPins[1], HIGH);
  delay(200);
  digitalWrite(ledPins[8], LOW);  
  digitalWrite(ledPins[1], LOW);
  delay(200);
  digitalWrite(ledPins[7], HIGH);  
  digitalWrite(ledPins[2], HIGH);
  delay(200);
  digitalWrite(ledPins[7], LOW);  
  digitalWrite(ledPins[2], LOW);
  delay(200);
  digitalWrite(ledPins[6], HIGH);  
  digitalWrite(ledPins[3], HIGH);
  delay(200);
  digitalWrite(ledPins[6], LOW);  
  digitalWrite(ledPins[3], LOW); 
  delay(200);
  digitalWrite(ledPins[5], HIGH);  
  digitalWrite(ledPins[4], HIGH);
  delay(200);
  digitalWrite(ledPins[5], LOW);  
  digitalWrite(ledPins[4], LOW);  
  delay(200);
  digitalWrite(ledPins[5], HIGH);  
  digitalWrite(ledPins[4], HIGH);
  delay(200);
  digitalWrite(ledPins[5], LOW);  
  digitalWrite(ledPins[4], LOW);
  delay(200);
  digitalWrite(ledPins[6], HIGH);  
  digitalWrite(ledPins[3], HIGH);
  delay(200);
  digitalWrite(ledPins[6], LOW);  
  digitalWrite(ledPins[3], LOW);
  delay(200);
  digitalWrite(ledPins[7], HIGH);  
  digitalWrite(ledPins[2], HIGH);
  delay(200);
  digitalWrite(ledPins[7], LOW);  
  digitalWrite(ledPins[2], LOW);
  delay(200);
  digitalWrite(ledPins[8], HIGH);  
  digitalWrite(ledPins[1], HIGH);
  delay(200);
  digitalWrite(ledPins[8], LOW);  
  digitalWrite(ledPins[1], LOW); 
  delay(200);
  digitalWrite(ledPins[9], HIGH);  
  digitalWrite(ledPins[0], HIGH);
  delay(200);
  digitalWrite(ledPins[9], LOW);  
  digitalWrite(ledPins[0], LOW);  
  delay(200);
  digitalWrite(ledPins[0], HIGH);  
  digitalWrite(ledPins[9], HIGH);
  delay(200);
  digitalWrite(ledPins[0], LOW);  
  digitalWrite(ledPins[9], LOW);
  delay(200);
  digitalWrite(ledPins[8], HIGH);  
  digitalWrite(ledPins[1], HIGH);
  delay(200);
  digitalWrite(ledPins[8], LOW);  
  digitalWrite(ledPins[1], LOW);
  delay(200);
  digitalWrite(ledPins[7], HIGH);  
  digitalWrite(ledPins[2], HIGH);
  delay(200);
  digitalWrite(ledPins[7], LOW);  
  digitalWrite(ledPins[2], LOW);
  delay(200);
  digitalWrite(ledPins[6], HIGH);  
  digitalWrite(ledPins[3], HIGH);
  delay(200);
  digitalWrite(ledPins[6], LOW);  
  digitalWrite(ledPins[3], LOW); 
  delay(200);
  digitalWrite(ledPins[5], HIGH);  
  digitalWrite(ledPins[4], HIGH);
  delay(200);
  digitalWrite(ledPins[5], LOW);  
  digitalWrite(ledPins[4], LOW);  
  delay(200);
  digitalWrite(ledPins[5], HIGH);  
  digitalWrite(ledPins[4], HIGH);
  delay(200);
  digitalWrite(ledPins[5], LOW);  
  digitalWrite(ledPins[4], LOW);
  delay(200);
  digitalWrite(ledPins[6], HIGH);  
  digitalWrite(ledPins[3], HIGH);
  delay(200);
  digitalWrite(ledPins[6], LOW);  
  digitalWrite(ledPins[3], LOW);
  delay(200);
  digitalWrite(ledPins[7], HIGH);  
  digitalWrite(ledPins[2], HIGH);
  delay(200);
  digitalWrite(ledPins[7], LOW);  
  digitalWrite(ledPins[2], LOW);
  delay(200);
  digitalWrite(ledPins[8], HIGH);  
  digitalWrite(ledPins[1], HIGH);
  delay(200);
  digitalWrite(ledPins[8], LOW);  
  digitalWrite(ledPins[1], LOW); 
  delay(200);
  digitalWrite(ledPins[9], HIGH);  
  digitalWrite(ledPins[0], HIGH);
  delay(200);
  digitalWrite(ledPins[9], LOW);  
  digitalWrite(ledPins[0], LOW);  
  delay(200);
  digitalWrite(ledPins[0], HIGH);  
  digitalWrite(ledPins[9], HIGH);
  delay(200);
  digitalWrite(ledPins[0], LOW);  
  digitalWrite(ledPins[9], LOW);
  delay(200);
  digitalWrite(ledPins[0], HIGH);  
  delay(400);            
  digitalWrite(ledPins[0], LOW);  
  digitalWrite(ledPins[1], HIGH); 
  delay(300);            
  digitalWrite(ledPins[1], LOW);   
  digitalWrite(ledPins[2], HIGH);  
  delay(300);                
  digitalWrite(ledPins[2], LOW); 
  digitalWrite(ledPins[3], HIGH);  
  delay(300);                
  digitalWrite(ledPins[3], LOW); 
  digitalWrite(ledPins[4], HIGH);  
  delay(100);                
  digitalWrite(ledPins[4], LOW); 
  digitalWrite(ledPins[5], HIGH);  
  delay(200);             
  digitalWrite(ledPins[5], LOW);    
  digitalWrite(ledPins[6], HIGH);  
  delay(200);       
  digitalWrite(ledPins[6], LOW);          
  digitalWrite(ledPins[7], HIGH);  
  delay(400);               
  digitalWrite(ledPins[7], LOW); 
  digitalWrite(ledPins[8], HIGH);
  delay(200);           
  digitalWrite(ledPins[8], LOW);      
  digitalWrite(ledPins[9], HIGH); 
  delay(200);
  digitalWrite(ledPins[9], LOW); 
  
  digitalWrite(ledPins[0], HIGH);  
  delay(100);            
  digitalWrite(ledPins[0], LOW);  
  digitalWrite(ledPins[1], HIGH); 
  delay(150);            
  digitalWrite(ledPins[1], LOW);   
  digitalWrite(ledPins[2], HIGH);  
  delay(100);                
  digitalWrite(ledPins[2], LOW); 
  digitalWrite(ledPins[3], HIGH);  
  delay(100);                
  digitalWrite(ledPins[3], LOW); 
  digitalWrite(ledPins[4], HIGH);  
  delay(150);                
  digitalWrite(ledPins[4], LOW); 
  digitalWrite(ledPins[5], HIGH);  
  delay(100);             
  digitalWrite(ledPins[5], LOW);    
  digitalWrite(ledPins[6], HIGH);  
  delay(100);       
  digitalWrite(ledPins[6], LOW);          
  digitalWrite(ledPins[7], HIGH);  
  delay(150);               
  digitalWrite(ledPins[7], LOW); 
  digitalWrite(ledPins[8], HIGH);
  delay(100);           
  digitalWrite(ledPins[8], LOW);      
  digitalWrite(ledPins[9], HIGH); 
  delay(100);
  digitalWrite(ledPins[9], LOW);
  digitalWrite(ledPins[4], HIGH);
  delay(delayTime);
  digitalWrite(ledPins[5], HIGH);    
  delay(delayTime);         
  digitalWrite(ledPins[3], HIGH);  
  delay(delayTime); 
  digitalWrite(ledPins[6], HIGH);  
  delay(delayTime); 
  digitalWrite(ledPins[2], HIGH);
  delay(delayTime);   
  digitalWrite(ledPins[7], HIGH); 
  delay(delayTime);  
  digitalWrite(ledPins[1], HIGH);
  delay(delayTime);   
  digitalWrite(ledPins[8], HIGH);
  delay(delayTime);
  digitalWrite(ledPins[0], HIGH);
  delay(delayTime);
  digitalWrite(ledPins[9], HIGH);
  delay(delayTime);
  digitalWrite(ledPins[9], LOW);
  delay(delayTime);
  digitalWrite(ledPins[0], LOW);
  delay(delayTime);             
  digitalWrite(ledPins[8], LOW);
  delay(delayTime);   
  digitalWrite(ledPins[1], LOW); 
  delay(delayTime);  
  digitalWrite(ledPins[7], LOW);
  delay(delayTime);   
  digitalWrite(ledPins[2], LOW);
  delay(delayTime);   
  digitalWrite(ledPins[6], LOW);
  delay(delayTime);   
  digitalWrite(ledPins[3], LOW);
  delay(delayTime);
  digitalWrite(ledPins[5], LOW);
  delay(delayTime);
  digitalWrite(ledPins[4], LOW);
  delay(delayTime);
  digitalWrite(ledPins[0], HIGH);
  delay(delayTime);
  digitalWrite(ledPins[9], HIGH);    
  delay(delayTime);         
  digitalWrite(ledPins[1], HIGH);  
  delay(delayTime); 
  digitalWrite(ledPins[8], HIGH);  
  delay(delayTime); 
  digitalWrite(ledPins[2], HIGH);
  delay(delayTime);   
  digitalWrite(ledPins[7], HIGH); 
  delay(delayTime);  
  digitalWrite(ledPins[3], HIGH);
  delay(delayTime);   
  digitalWrite(ledPins[6], HIGH);
  delay(delayTime);
  digitalWrite(ledPins[4], HIGH);
  delay(delayTime);
  digitalWrite(ledPins[5], HIGH);
  delay(delayTime);
  digitalWrite(ledPins[9], LOW);
  delay(delayTime);
  digitalWrite(ledPins[0], LOW);
  delay(delayTime);             
  digitalWrite(ledPins[1], LOW);
  delay(delayTime);   
  digitalWrite(ledPins[8], LOW); 
  delay(delayTime);  
  digitalWrite(ledPins[2], LOW);
  delay(delayTime);   
  digitalWrite(ledPins[7], LOW);
  delay(delayTime);   
  digitalWrite(ledPins[3], LOW);
  delay(delayTime);   
  digitalWrite(ledPins[6], LOW);
  delay(delayTime);
  digitalWrite(ledPins[4], LOW);
  delay(delayTime);
  digitalWrite(ledPins[5], LOW);
  delay(delayTime);
  
  digitalWrite(ledPins[4], HIGH);
  delay(delayTime);
  digitalWrite(ledPins[5], HIGH);    
  delay(delayTime);         
  digitalWrite(ledPins[3], HIGH);  
  delay(delayTime); 
  digitalWrite(ledPins[6], HIGH);  
  delay(delayTime); 
  digitalWrite(ledPins[2], HIGH);
  delay(delayTime);   
  digitalWrite(ledPins[7], HIGH); 
  delay(delayTime);  
  digitalWrite(ledPins[1], HIGH);
  delay(delayTime);   
  digitalWrite(ledPins[8], HIGH);
  delay(delayTime);
  digitalWrite(ledPins[0], HIGH);
  delay(delayTime);
  digitalWrite(ledPins[9], HIGH);
  delay(delayTime);
  digitalWrite(ledPins[9], LOW);
  delay(delayTime);
  digitalWrite(ledPins[0], LOW);
  delay(delayTime);             
  digitalWrite(ledPins[8], LOW);
  delay(delayTime);   
  digitalWrite(ledPins[1], LOW); 
  delay(delayTime);  
  digitalWrite(ledPins[7], LOW);
  delay(delayTime);   
  digitalWrite(ledPins[2], LOW);
  delay(delayTime);   
  digitalWrite(ledPins[6], LOW);
  delay(delayTime);   
  digitalWrite(ledPins[3], LOW);
  delay(delayTime);
  digitalWrite(ledPins[5], LOW);
  delay(delayTime);
  digitalWrite(ledPins[4], LOW);
  delay(delayTime);
  digitalWrite(ledPins[0], HIGH);
  delay(delayTime);
  digitalWrite(ledPins[9], HIGH);    
  delay(delayTime);         
  digitalWrite(ledPins[1], HIGH);  
  delay(delayTime); 
  digitalWrite(ledPins[8], HIGH);  
  delay(delayTime); 
  digitalWrite(ledPins[2], HIGH);
  delay(delayTime);   
  digitalWrite(ledPins[7], HIGH); 
  delay(delayTime);  
  digitalWrite(ledPins[3], HIGH);
  delay(delayTime);   
  digitalWrite(ledPins[6], HIGH);
  delay(delayTime);
  digitalWrite(ledPins[4], HIGH);
  delay(delayTime);
  digitalWrite(ledPins[5], HIGH);
  delay(delayTime);
  digitalWrite(ledPins[9], LOW);
  delay(delayTime);
  digitalWrite(ledPins[0], LOW);
  delay(delayTime);             
  digitalWrite(ledPins[1], LOW);
  delay(delayTime);   
  digitalWrite(ledPins[8], LOW); 
  delay(delayTime);  
  digitalWrite(ledPins[2], LOW);
  delay(delayTime);   
  digitalWrite(ledPins[7], LOW);
  delay(delayTime);   
  digitalWrite(ledPins[3], LOW);
  delay(delayTime);   
  digitalWrite(ledPins[6], LOW);
  delay(delayTime);
  digitalWrite(ledPins[4], LOW);
  delay(delayTime);
  digitalWrite(ledPins[5], LOW);
  delay(delayTime);  
  
  digitalWrite(ledPins[0], HIGH);  
  digitalWrite(ledPins[9], HIGH);
  delay(200);
  digitalWrite(ledPins[0], LOW);  
  digitalWrite(ledPins[9], LOW);
  delay(200);
  digitalWrite(ledPins[8], HIGH);  
  digitalWrite(ledPins[1], HIGH);
  delay(200);
  digitalWrite(ledPins[8], LOW);  
  digitalWrite(ledPins[1], LOW);
  delay(200);
  digitalWrite(ledPins[7], HIGH);  
  digitalWrite(ledPins[2], HIGH);
  delay(200);
  digitalWrite(ledPins[7], LOW);  
  digitalWrite(ledPins[2], LOW);
  delay(200);
  digitalWrite(ledPins[6], HIGH);  
  digitalWrite(ledPins[3], HIGH);
  delay(200);
  digitalWrite(ledPins[6], LOW);  
  digitalWrite(ledPins[3], LOW); 
  delay(200);
  digitalWrite(ledPins[5], HIGH);  
  digitalWrite(ledPins[4], HIGH);
  delay(200);
  digitalWrite(ledPins[5], LOW);  
  digitalWrite(ledPins[4], LOW);  
  delay(200);
  digitalWrite(ledPins[5], HIGH);  
  digitalWrite(ledPins[4], HIGH);
  delay(200);
  digitalWrite(ledPins[5], LOW);  
  digitalWrite(ledPins[4], LOW);
  delay(200);
  digitalWrite(ledPins[6], HIGH);  
  digitalWrite(ledPins[3], HIGH);
  delay(200);
  digitalWrite(ledPins[6], LOW);  
  digitalWrite(ledPins[3], LOW);
  delay(200);
  digitalWrite(ledPins[7], HIGH);  
  digitalWrite(ledPins[2], HIGH);
  delay(200);
  digitalWrite(ledPins[7], LOW);  
  digitalWrite(ledPins[2], LOW);
  delay(200);
  digitalWrite(ledPins[8], HIGH);  
  digitalWrite(ledPins[1], HIGH);
  delay(200);
  digitalWrite(ledPins[8], LOW);  
  digitalWrite(ledPins[1], LOW); 
  delay(200);
  digitalWrite(ledPins[9], HIGH);  
  digitalWrite(ledPins[0], HIGH);
  delay(200);
  digitalWrite(ledPins[9], LOW);  
  digitalWrite(ledPins[0], LOW);  
  delay(200);
  digitalWrite(ledPins[0], HIGH);  
  digitalWrite(ledPins[9], HIGH);
  delay(200);
  digitalWrite(ledPins[0], LOW);  
  digitalWrite(ledPins[9], LOW);
  delay(200);
  digitalWrite(ledPins[8], HIGH);  
  digitalWrite(ledPins[1], HIGH);
  delay(200);
  digitalWrite(ledPins[8], LOW);  
  digitalWrite(ledPins[1], LOW);
  delay(200);
  digitalWrite(ledPins[7], HIGH);  
  digitalWrite(ledPins[2], HIGH);
  delay(200);
  digitalWrite(ledPins[7], LOW);  
  digitalWrite(ledPins[2], LOW);
  delay(200);
  digitalWrite(ledPins[6], HIGH);  
  digitalWrite(ledPins[3], HIGH);
  delay(200);
  digitalWrite(ledPins[6], LOW);  
  digitalWrite(ledPins[3], LOW); 
  delay(200);
  digitalWrite(ledPins[5], HIGH);  
  digitalWrite(ledPins[4], HIGH);
  delay(200);
  digitalWrite(ledPins[5], LOW);  
  digitalWrite(ledPins[4], LOW);  
  delay(200);
  digitalWrite(ledPins[5], HIGH);  
  digitalWrite(ledPins[4], HIGH);
  delay(200);
  digitalWrite(ledPins[5], LOW);  
  digitalWrite(ledPins[4], LOW);
  delay(200);
  digitalWrite(ledPins[6], HIGH);  
  digitalWrite(ledPins[3], HIGH);
  delay(200);
  digitalWrite(ledPins[6], LOW);  
  digitalWrite(ledPins[3], LOW);
  delay(200);
  digitalWrite(ledPins[7], HIGH);  
  digitalWrite(ledPins[2], HIGH);
  delay(200);
  digitalWrite(ledPins[7], LOW);  
  digitalWrite(ledPins[2], LOW);
  delay(200);
  digitalWrite(ledPins[8], HIGH);  
  digitalWrite(ledPins[1], HIGH);
  delay(200);
  digitalWrite(ledPins[8], LOW);  
  digitalWrite(ledPins[1], LOW); 
  delay(200);
  digitalWrite(ledPins[9], HIGH);  
  digitalWrite(ledPins[0], HIGH);
  delay(200);
  digitalWrite(ledPins[9], LOW);  
  digitalWrite(ledPins[0], LOW);  
  delay(200);
  digitalWrite(ledPins[0], HIGH);  
  digitalWrite(ledPins[9], HIGH);
  delay(200);
  digitalWrite(ledPins[0], LOW);  
  digitalWrite(ledPins[9], LOW);
  delay(200);
  digitalWrite(ledPins[8], HIGH);  
  digitalWrite(ledPins[1], HIGH);
  delay(200);
  digitalWrite(ledPins[8], LOW);  
  digitalWrite(ledPins[1], LOW);
  delay(200);
  digitalWrite(ledPins[7], HIGH);  
  digitalWrite(ledPins[2], HIGH);
  delay(200);
  digitalWrite(ledPins[7], LOW);  
  digitalWrite(ledPins[2], LOW);
  delay(200);
  digitalWrite(ledPins[6], HIGH);  
  digitalWrite(ledPins[3], HIGH);
  delay(200);
  digitalWrite(ledPins[6], LOW);  
  digitalWrite(ledPins[3], LOW); 
  delay(200);
  digitalWrite(ledPins[5], HIGH);  
  digitalWrite(ledPins[4], HIGH);
  delay(200);
  digitalWrite(ledPins[5], LOW);  
  digitalWrite(ledPins[4], LOW);  
  delay(200);
  digitalWrite(ledPins[5], HIGH);  
  digitalWrite(ledPins[4], HIGH);
  delay(200);
  digitalWrite(ledPins[5], LOW);  
  digitalWrite(ledPins[4], LOW);
  delay(200);
  digitalWrite(ledPins[6], HIGH);  
  digitalWrite(ledPins[3], HIGH);
  delay(200);
  digitalWrite(ledPins[6], LOW);  
  digitalWrite(ledPins[3], LOW);
  delay(200);
  digitalWrite(ledPins[7], HIGH);  
  digitalWrite(ledPins[2], HIGH);
  delay(200);
  digitalWrite(ledPins[7], LOW);  
  digitalWrite(ledPins[2], LOW);
  delay(200);
  digitalWrite(ledPins[8], HIGH);  
  digitalWrite(ledPins[1], HIGH);
  delay(200);
  digitalWrite(ledPins[8], LOW);  
  digitalWrite(ledPins[1], LOW); 
  delay(200);
  digitalWrite(ledPins[9], HIGH);  
  digitalWrite(ledPins[0], HIGH);
  delay(200);
  digitalWrite(ledPins[9], LOW);  
  digitalWrite(ledPins[0], LOW);  
  delay(200);
  digitalWrite(ledPins[0], HIGH);  
  digitalWrite(ledPins[9], HIGH);
  delay(200);
  digitalWrite(ledPins[0], LOW);  
  digitalWrite(ledPins[9], LOW);
  delay(200);
  digitalWrite(ledPins[0], HIGH);  
  delay(400);            
  digitalWrite(ledPins[0], LOW);  
  digitalWrite(ledPins[1], HIGH); 
  delay(300);            
  digitalWrite(ledPins[1], LOW);   
  digitalWrite(ledPins[2], HIGH);  
  delay(300);                
  digitalWrite(ledPins[2], LOW); 
  digitalWrite(ledPins[3], HIGH);  
  delay(300);                
  digitalWrite(ledPins[3], LOW); 
  digitalWrite(ledPins[4], HIGH);  
  delay(100);                
  digitalWrite(ledPins[4], LOW); 
  digitalWrite(ledPins[5], HIGH);  
  delay(200);             
  digitalWrite(ledPins[5], LOW);    
  digitalWrite(ledPins[6], HIGH);  
  delay(200);       
  digitalWrite(ledPins[6], LOW);          
  digitalWrite(ledPins[7], HIGH);  
  delay(400);               
  digitalWrite(ledPins[7], LOW); 
  digitalWrite(ledPins[8], HIGH);
  delay(200);           
  digitalWrite(ledPins[8], LOW);      
  digitalWrite(ledPins[9], HIGH); 
  delay(200);
  digitalWrite(ledPins[9], LOW); 
  
  digitalWrite(ledPins[0], HIGH);  
  delay(100);            
  digitalWrite(ledPins[0], LOW);  
  digitalWrite(ledPins[1], HIGH); 
  delay(150);            
  digitalWrite(ledPins[1], LOW);   
  digitalWrite(ledPins[2], HIGH);  
  delay(100);                
  digitalWrite(ledPins[2], LOW); 
  digitalWrite(ledPins[3], HIGH);  
  delay(100);                
  digitalWrite(ledPins[3], LOW); 
  digitalWrite(ledPins[4], HIGH);  
  delay(150);                
  digitalWrite(ledPins[4], LOW); 
  digitalWrite(ledPins[5], HIGH);  
  delay(100);             
  digitalWrite(ledPins[5], LOW);    
  digitalWrite(ledPins[6], HIGH);  
  delay(100);       
  digitalWrite(ledPins[6], LOW);          
  digitalWrite(ledPins[7], HIGH);  
  delay(150);               
  digitalWrite(ledPins[7], LOW); 
  digitalWrite(ledPins[8], HIGH);
  delay(100);           
  digitalWrite(ledPins[8], LOW);      
  digitalWrite(ledPins[9], HIGH); 
  delay(100);
  digitalWrite(ledPins[9], LOW);
  digitalWrite(ledPins[4], HIGH);
  delay(delayTime);
  digitalWrite(ledPins[5], HIGH);    
  delay(delayTime);         
  digitalWrite(ledPins[3], HIGH);  
  delay(delayTime); 
  digitalWrite(ledPins[6], HIGH);  
  delay(delayTime); 
  digitalWrite(ledPins[2], HIGH);
  delay(delayTime);   
  digitalWrite(ledPins[7], HIGH); 
  delay(delayTime);  
  digitalWrite(ledPins[1], HIGH);
  delay(delayTime);   
  digitalWrite(ledPins[8], HIGH);
  delay(delayTime);
  digitalWrite(ledPins[0], HIGH);
  delay(delayTime);
  digitalWrite(ledPins[9], HIGH);
  delay(delayTime);
  digitalWrite(ledPins[9], LOW);
  delay(delayTime);
  digitalWrite(ledPins[0], LOW);
  delay(delayTime);             
  digitalWrite(ledPins[8], LOW);
  delay(delayTime);   
  digitalWrite(ledPins[1], LOW); 
  delay(delayTime);  
  digitalWrite(ledPins[7], LOW);
  delay(delayTime);   
  digitalWrite(ledPins[2], LOW);
  delay(delayTime);   
  digitalWrite(ledPins[6], LOW);
  delay(delayTime);   
  digitalWrite(ledPins[3], LOW);
  delay(delayTime);
  digitalWrite(ledPins[5], LOW);
  delay(delayTime);
  digitalWrite(ledPins[4], LOW);
  delay(delayTime);
  digitalWrite(ledPins[0], HIGH);
  delay(delayTime);
  digitalWrite(ledPins[9], HIGH);    
  delay(delayTime);         
  digitalWrite(ledPins[1], HIGH);  
  delay(delayTime); 
  digitalWrite(ledPins[8], HIGH);  
  delay(delayTime); 
  digitalWrite(ledPins[2], HIGH);
  delay(delayTime);   
  digitalWrite(ledPins[7], HIGH); 
  delay(delayTime);  
  digitalWrite(ledPins[3], HIGH);
  delay(delayTime);   
  digitalWrite(ledPins[6], HIGH);
  delay(delayTime);
  digitalWrite(ledPins[4], HIGH);
  delay(delayTime);
  digitalWrite(ledPins[5], HIGH);
  delay(delayTime);
  digitalWrite(ledPins[9], LOW);
  delay(delayTime);
  digitalWrite(ledPins[0], LOW);
  delay(delayTime);             
  digitalWrite(ledPins[1], LOW);
  delay(delayTime);   
  digitalWrite(ledPins[8], LOW); 
  delay(delayTime);  
  digitalWrite(ledPins[2], LOW);
  delay(delayTime);   
  digitalWrite(ledPins[7], LOW);
  delay(delayTime);   
  digitalWrite(ledPins[3], LOW);
  delay(delayTime);   
  digitalWrite(ledPins[6], LOW);
  delay(delayTime);
  digitalWrite(ledPins[4], LOW);
  delay(delayTime);
  digitalWrite(ledPins[5], LOW);
  delay(delayTime);
  
  digitalWrite(ledPins[4], HIGH);
  delay(delayTime);
  digitalWrite(ledPins[5], HIGH);    
  delay(delayTime);         
  digitalWrite(ledPins[3], HIGH);  
  delay(delayTime); 
  digitalWrite(ledPins[6], HIGH);  
  delay(delayTime); 
  digitalWrite(ledPins[2], HIGH);
  delay(delayTime);   
  digitalWrite(ledPins[7], HIGH); 
  delay(delayTime);  
  digitalWrite(ledPins[1], HIGH);
  delay(delayTime);   
  digitalWrite(ledPins[8], HIGH);
  delay(delayTime);
  digitalWrite(ledPins[0], HIGH);
  delay(delayTime);
  digitalWrite(ledPins[9], HIGH);
  delay(delayTime);
  digitalWrite(ledPins[9], LOW);
  delay(delayTime);
  digitalWrite(ledPins[0], LOW);
  delay(delayTime);             
  digitalWrite(ledPins[8], LOW);
  delay(delayTime);   
  digitalWrite(ledPins[1], LOW); 
  delay(delayTime);  
  digitalWrite(ledPins[7], LOW);
  delay(delayTime);   
  digitalWrite(ledPins[2], LOW);
  delay(delayTime);   
  digitalWrite(ledPins[6], LOW);
  delay(delayTime);   
  digitalWrite(ledPins[3], LOW);
  delay(delayTime);
  digitalWrite(ledPins[5], LOW);
  delay(delayTime);
  digitalWrite(ledPins[4], LOW);
  delay(delayTime);
  digitalWrite(ledPins[0], HIGH);
  delay(delayTime);
  digitalWrite(ledPins[9], HIGH);    
  delay(delayTime);         
  digitalWrite(ledPins[1], HIGH);  
  delay(delayTime); 
  digitalWrite(ledPins[8], HIGH);  
  delay(delayTime); 
  digitalWrite(ledPins[2], HIGH);
  delay(delayTime);   
  digitalWrite(ledPins[7], HIGH); 
  delay(delayTime);  
  digitalWrite(ledPins[3], HIGH);
  delay(delayTime);   
  digitalWrite(ledPins[6], HIGH);
  delay(delayTime);
  digitalWrite(ledPins[4], HIGH);
  delay(delayTime);
  digitalWrite(ledPins[5], HIGH);
  delay(delayTime);
  digitalWrite(ledPins[9], LOW);
  delay(delayTime);
  digitalWrite(ledPins[0], LOW);
  delay(delayTime);             
  digitalWrite(ledPins[1], LOW);
  delay(delayTime);   
  digitalWrite(ledPins[8], LOW); 
  delay(delayTime);  
  digitalWrite(ledPins[2], LOW);
  delay(delayTime);   
  digitalWrite(ledPins[7], LOW);
  delay(delayTime);   
  digitalWrite(ledPins[3], LOW);
  delay(delayTime);   
  digitalWrite(ledPins[6], LOW);
  delay(delayTime);
  digitalWrite(ledPins[4], LOW);
  delay(delayTime);
  digitalWrite(ledPins[5], LOW);
  delay(delayTime);  
  
  digitalWrite(ledPins[0], HIGH);  
  digitalWrite(ledPins[9], HIGH);
  delay(200);
  digitalWrite(ledPins[0], LOW);  
  digitalWrite(ledPins[9], LOW);
  delay(200);
  digitalWrite(ledPins[8], HIGH);  
  digitalWrite(ledPins[1], HIGH);
  delay(200);
  digitalWrite(ledPins[8], LOW);  
  digitalWrite(ledPins[1], LOW);
  delay(200);
  digitalWrite(ledPins[7], HIGH);  
  digitalWrite(ledPins[2], HIGH);
  delay(200);
  digitalWrite(ledPins[7], LOW);  
  digitalWrite(ledPins[2], LOW);
  delay(200);
  digitalWrite(ledPins[6], HIGH);  
  digitalWrite(ledPins[3], HIGH);
  delay(200);
  digitalWrite(ledPins[6], LOW);  
  digitalWrite(ledPins[3], LOW); 
  delay(200);
  digitalWrite(ledPins[5], HIGH);  
  digitalWrite(ledPins[4], HIGH);
  delay(200);
  digitalWrite(ledPins[5], LOW);  
  digitalWrite(ledPins[4], LOW);  
  delay(200);
  digitalWrite(ledPins[5], HIGH);  
  digitalWrite(ledPins[4], HIGH);
  delay(100);
  digitalWrite(ledPins[5], LOW);  
  digitalWrite(ledPins[4], LOW);
  delay(100);
  digitalWrite(ledPins[6], HIGH);  
  digitalWrite(ledPins[3], HIGH);
  delay(100);
  digitalWrite(ledPins[6], LOW);  
  digitalWrite(ledPins[3], LOW);
  delay(100);
  digitalWrite(ledPins[7], HIGH);  
  digitalWrite(ledPins[2], HIGH);
  delay(100);
  digitalWrite(ledPins[7], LOW);  
  digitalWrite(ledPins[2], LOW);
  delay(100);
  digitalWrite(ledPins[8], HIGH);  
  digitalWrite(ledPins[1], HIGH);
  delay(100);
  digitalWrite(ledPins[8], LOW);  
  digitalWrite(ledPins[1], LOW); 
  delay(100);
  digitalWrite(ledPins[9], HIGH);  
  digitalWrite(ledPins[0], HIGH);
  delay(100);
  digitalWrite(ledPins[9], LOW);  
  digitalWrite(ledPins[0], LOW);  
  delay(100);
  digitalWrite(ledPins[0], HIGH);  
  digitalWrite(ledPins[9], HIGH);
  delay(100);
  digitalWrite(ledPins[0], LOW);  
  digitalWrite(ledPins[9], LOW);
  delay(100);
  digitalWrite(ledPins[8], HIGH);  
  digitalWrite(ledPins[1], HIGH);
  delay(100);
  digitalWrite(ledPins[8], LOW);  
  digitalWrite(ledPins[1], LOW);
  delay(100);
  digitalWrite(ledPins[7], HIGH);  
  digitalWrite(ledPins[2], HIGH);
  delay(100);
  digitalWrite(ledPins[7], LOW);  
  digitalWrite(ledPins[2], LOW);
  delay(100);
  digitalWrite(ledPins[6], HIGH);  
  digitalWrite(ledPins[3], HIGH);
  delay(100);
  digitalWrite(ledPins[6], LOW);  
  digitalWrite(ledPins[3], LOW); 
  delay(100);
  digitalWrite(ledPins[5], HIGH);  
  digitalWrite(ledPins[4], HIGH);
  delay(100);
  digitalWrite(ledPins[5], LOW);  
  digitalWrite(ledPins[4], LOW);  
  delay(100);
  digitalWrite(ledPins[5], HIGH);  
  digitalWrite(ledPins[4], HIGH);
  delay(100);
  digitalWrite(ledPins[5], LOW);  
  digitalWrite(ledPins[4], LOW);
  delay(100);
  digitalWrite(ledPins[6], HIGH);  
  digitalWrite(ledPins[3], HIGH);
  delay(100);
  digitalWrite(ledPins[6], LOW);  
  digitalWrite(ledPins[3], LOW);
  delay(100);
  digitalWrite(ledPins[7], HIGH);  
  digitalWrite(ledPins[2], HIGH);
  delay(100);
  digitalWrite(ledPins[7], LOW);  
  digitalWrite(ledPins[2], LOW);
  delay(100);
  digitalWrite(ledPins[8], HIGH);  
  digitalWrite(ledPins[1], HIGH);
  delay(100);
  digitalWrite(ledPins[8], LOW);  
  digitalWrite(ledPins[1], LOW); 
  delay(100);
  digitalWrite(ledPins[9], HIGH);  
  digitalWrite(ledPins[0], HIGH);
  delay(100);
  digitalWrite(ledPins[9], LOW);  
  digitalWrite(ledPins[0], LOW);  
  delay(100);
  digitalWrite(ledPins[0], HIGH);  
  digitalWrite(ledPins[9], HIGH);
  delay(100);
  digitalWrite(ledPins[0], LOW);  
  digitalWrite(ledPins[9], LOW);
  delay(100);
  digitalWrite(ledPins[8], HIGH);  
  digitalWrite(ledPins[1], HIGH);
  delay(100);
  digitalWrite(ledPins[8], LOW);  
  digitalWrite(ledPins[1], LOW);
  delay(100);
  digitalWrite(ledPins[7], HIGH);  
  digitalWrite(ledPins[2], HIGH);
  delay(100);
  digitalWrite(ledPins[7], LOW);  
  digitalWrite(ledPins[2], LOW);
  delay(100);
  digitalWrite(ledPins[6], HIGH);  
  digitalWrite(ledPins[3], HIGH);
  delay(100);
  digitalWrite(ledPins[6], LOW);  
  digitalWrite(ledPins[3], LOW); 
  delay(100);
  digitalWrite(ledPins[5], HIGH);  
  digitalWrite(ledPins[4], HIGH);
  delay(100);
  digitalWrite(ledPins[5], LOW);  
  digitalWrite(ledPins[4], LOW);  
  delay(100);
  digitalWrite(ledPins[5], HIGH);  
  digitalWrite(ledPins[4], HIGH);
  delay(100);
  digitalWrite(ledPins[5], LOW);  
  digitalWrite(ledPins[4], LOW);
  delay(100);
  digitalWrite(ledPins[6], HIGH);  
  digitalWrite(ledPins[3], HIGH);
  delay(100);
  digitalWrite(ledPins[6], LOW);  
  digitalWrite(ledPins[3], LOW);
  delay(100);
  digitalWrite(ledPins[7], HIGH);  
  digitalWrite(ledPins[2], HIGH);
  delay(100);
  digitalWrite(ledPins[7], LOW);  
  digitalWrite(ledPins[2], LOW);
  delay(100);
  digitalWrite(ledPins[8], HIGH);  
  digitalWrite(ledPins[1], HIGH);
  delay(100);
  digitalWrite(ledPins[8], LOW);  
  digitalWrite(ledPins[1], LOW); 
  delay(100);
  digitalWrite(ledPins[9], HIGH);  
  digitalWrite(ledPins[0], HIGH);
  delay(100);
  digitalWrite(ledPins[9], LOW);  
  digitalWrite(ledPins[0], LOW);  
  delay(100);
  digitalWrite(ledPins[0], HIGH);  
  digitalWrite(ledPins[9], HIGH);
  delay(100);
  digitalWrite(ledPins[0], LOW);  
  digitalWrite(ledPins[9], LOW);
  delay(100);
  while(1);
}

void oneAfterAnotherLoop(){
  int index;
  int delayTime = 100; 
  for(index = 0; index <= 9; index++)
  {
    digitalWrite(ledPins[index], HIGH);
    delay(delayTime);                
  }                                  
  for(index = 9; index >= 0; index--)
  {
    digitalWrite(ledPins[index], LOW);
    delay(delayTime);
  }               
}

void oneOnAtATime()
{
  int index;
  int delayTime = 100; 

  for(index = 0; index <= 9; index++)
  {
    digitalWrite(ledPins[index], HIGH);  
    delay(delayTime);
    digitalWrite(ledPins[index], LOW);
  }
}

void pingPong()
{
  int index;
  int delayTime = 100; 
  
  for(index = 0; index <= 9; index++)
  {
    digitalWrite(ledPins[index], HIGH); 
    delay(delayTime);                    
    digitalWrite(ledPins[index], LOW);
  }

  // step through the LEDs, from 5 to 0

  for(index = 12; index >= 0; index--)
  {
    digitalWrite(ledPins[index], HIGH);
    delay(delayTime);
    digitalWrite(ledPins[index], LOW);
  }
}

void marquee()
{
  int index;
  int delayTime = 200; 
  for(index = 0; index <= 2; index++) 
  {
    digitalWrite(ledPins[index], HIGH);    
    digitalWrite(ledPins[index+3], HIGH);
    delay(delayTime);
    digitalWrite(ledPins[index], LOW);
    digitalWrite(ledPins[index+3], LOW);
  }
}

void randomLED()
{
  int index;
  int delayTime;

  index = random(5); 
  delayTime = 100;

  digitalWrite(ledPins[index], HIGH);  
  delay(delayTime);
  digitalWrite(ledPins[index], LOW);  
}
